### ISSUE TITLE
Don't want to count external files

### ISSUE THREAD

**Issue by BLLuis** [DarioCasciato/vscode-codequantum#2]
In my workspace or folder I include many external folders that I don't want to count because is not my code, for example library include files, I program in C.
I found no way to exclude that folders from being counted, I try to make a .ignore file and put the path on the folder, verbatim and using the .gitignore patterns but no luck.
Any advice?

My .code-workspace file as example:

`"folders": [
		{
			"path": "."
		},
		{
			"path": "../../somePath1/ExternalFiles"
		},
		{
			"path": "../../somePath2/LibsHeaders"
		},
		{
			"path": "../../somePath3/ThirdPartyFiles"
		}
	],`

In this example my code is under . (first entry) and all the external code is under ../../somewhere, but some of my code could be somewhere too, so, a useful thing is to exclude some paths from count, just to count our code.

EDIT: added a fragment of my workspace file.

Thanks.

**Comment by DarioCasciato** [comment]
Hi @BLLuis, I will follow this problem and update you on new changes/version. You can expect a new release this week!

Regards
Dario

**Comment by DarioCasciato** [comment]
Sure, here's a more concise response:

---

Hi @BLLuis ,

I've updated the extension to handle the `.gitignore` correctly and added a feature to exclude files and directories via `.vscode/settings.json`. You can now specify patterns like `"../../somePath1/ExternalFiles/**"` in the settings to exclude those folders from the line count. You can get more information in the new readme!

You can download the new version here:
[https://open-vsx.org/extension/DarioCas/codequantum](https://open-vsx.org/extension/DarioCas/codequantum)
or here:
[https://github.com/DarioCasciato/vscode-codequantum/releases/tag/1.2.0](https://github.com/DarioCasciato/vscode-codequantum/releases/tag/1.2.0)

Please update to the latest version to see these improvements. Let me know if you encounter any other issues!

Best regards,
Dario
